services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: /bin/ash -c 'npm run build && npm start'
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
